// This file is auto-generated. Don't edit it manually
// Generated from: src/assets/icons/
// Last updated: 2025-06-28T13:40:49.335Z

export type IconName =
  | 'approve'
  | 'attachment'
  | 'chat'
  | 'check'
  | 'checkmark'
  | 'close'
  | 'delete'
  | 'edit'
  | 'face-smiling'
  | 'git'
  | 'google'
  | 'job-in-company'
  | 'menu-list'
  | 'microphone-off'
  | 'microphone'
  | 'music'
  | 'pause'
  | 'phone'
  | 'play'
  | 'profile'
  | 'publish'
  | 'screen-share-off'
  | 'screen-share-on'
  | 'search'
  | 'send'
  | 'sign-out'
  | 'sound'
  | 'studying-university'
  | 'thumb-down'
  | 'thump-up'
  | 'video-camera'
  | 'video'
  | 'videocam-off'
  | 'videocam-on'
  | 'work-position'
