export * from './getTranslate'
export * from './getMessages'

export * from './rem'
export * from './makeCn'
export * from './logColors'
export * from './isArray'
export * from './isObject'
export * from './isNumber'
export * from './isSameType'
export * from './isNull'
export * from './isUndefined'
export * from './isNil'
export * from './isString'
export * from './throttle'
export * from './debounce'
