declare module 'prismjs/components/prism-typescript'
declare module 'prismjs/components/prism-javascript'
declare module 'prismjs/components/prism-python'
declare module 'prismjs/components/prism-java'
declare module 'prismjs/components/prism-cpp'
